# Generated by Django 5.2 on 2025-10-26 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeritem',
            name='item_model',
            field=models.CharField(max_length=100, default=''),
        ),
        migrations.AddField(
            model_name='customeritem',
            name='original_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, default=0),
        ),
        migrations.AddField(
            model_name='customeritem',
            name='downpayment',
            field=models.DecimalField(decimal_places=2, max_digits=10, default=0),
        ),
        migrations.AddField(
            model_name='customeritem',
            name='good_as_cash',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AddField(
            model_name='customeritem',
            name='rebate_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='customeritem',
            name='monthly_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='customeritem',
            name='term_months',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customeritem',
            name='total_contract_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, default=0),
        ),
        migrations.AddField(
            model_name='customeritem',
            name='purchase_date',
            field=models.DateField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='customeritem',
            name='contract_start_date',
            field=models.DateField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='customeritem',
            name='contract_end_date',
            field=models.DateField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='customeritem',
            name='first_due_date',
            field=models.DateField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='customeritem',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('pulled_out', 'Pulled Out')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='customeritem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
