# Generated by Django 5.2 on 2025-10-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20251026_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeritem',
            name='downpayment',
            field=models.DecimalField(decimal_places=2, max_digits=10, default=0),
        ),
    ]
