# Generated by Django 5.2 on 2025-10-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20251026_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeritem',
            name='item_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
