# Generated by Django 5.2 on 2025-10-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20251026_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeritem',
            name='item_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
