# Generated by Django 5.2 on 2025-10-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20251026_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeritem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
