# Generated by Django 5.2 on 2025-10-26 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20251026_2236'),
    ]

    operations = [
    ]
