# Generated by Django 5.2 on 2025-11-02 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_fix_transaction_number_constraint'),
    ]

    operations = [
    ]
